// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} scrollContainerName
 * @returns {Promise.<void>}
 */
export async function Chatroom_ScrollDown(scrollContainerName) {
	// BEGIN USER CODE

	let classname = ".mx-name-" + scrollContainerName;
	let sc = null;
	let count = 0;
	while (count < 40 && sc === null) {
		await new Promise(r => setTimeout(r, 250));
		sc = document.querySelector(classname + " > .mx-dataview-content");
	}
	sc && sc.scroll({
		top: sc.scrollHeight,
		behavior: "smooth"
	});

	// END USER CODE
}
