// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ezwebsocket.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ezwebsocket.WebsocketUtils;

/**
 * Use this inside your after startup flow to initialize the websocket server
 * 
 * 
 */
public class JA_AddWebsocketEndpoint_WithOnCloseMicroflow extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String websocketIdentifier;
	private java.lang.Long sessionTimeout;
	private java.lang.String onCloseMicroflow;
	private java.lang.String onCloseMicroflowParameterKey;

	public JA_AddWebsocketEndpoint_WithOnCloseMicroflow(IContext context, java.lang.String websocketIdentifier, java.lang.Long sessionTimeout, java.lang.String onCloseMicroflow, java.lang.String onCloseMicroflowParameterKey)
	{
		super(context);
		this.websocketIdentifier = websocketIdentifier;
		this.sessionTimeout = sessionTimeout;
		this.onCloseMicroflow = onCloseMicroflow;
		this.onCloseMicroflowParameterKey = onCloseMicroflowParameterKey;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		WebsocketUtils.addWebsocketEndpointWithOnCloseMicroflow(websocketIdentifier, sessionTimeout, onCloseMicroflow,
				onCloseMicroflowParameterKey);
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_AddWebsocketEndpoint_WithOnCloseMicroflow";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
