// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ezwebsocket.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ezwebsocket.WebsocketUtils;

/**
 * Notifies all the clients subscribed to the context object with an action trigger
 * In the client widget, configure the action that should be executed
 */
public class JA_Notify extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String websocketIdentifier;
	private java.lang.String objectId;
	private java.lang.String action;
	private java.lang.String message;

	public JA_Notify(IContext context, java.lang.String websocketIdentifier, java.lang.String objectId, java.lang.String action, java.lang.String message)
	{
		super(context);
		this.websocketIdentifier = websocketIdentifier;
		this.objectId = objectId;
		this.action = action;
		this.message = message;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		WebsocketUtils.notify(objectId, action, message, websocketIdentifier);
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_Notify";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
